# Generated by Django 2.2 on 2019-04-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('site_url', models.TextField()),
                ('photo_url', models.TextField()),
                ('length', models.CharField(max_length=255)),
                ('max_elv', models.CharField(max_length=255)),
                ('min_elv', models.CharField(max_length=255)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='mtb_trails_app.Park')),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mtb_trails_app.State'),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('tire_size', models.CharField(max_length=255)),
                ('tubeless', models.BooleanField(default=False)),
                ('groupset', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('full_suspension', models.BooleanField(default=False)),
                ('dropper_post', models.BooleanField(default=False)),
                ('photo_url', models.CharField(blank=True, max_length=400)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='mtb_trails_app.Trail')),
            ],
        ),
    ]
