# Generated by Django 2.2 on 2019-04-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_trails_app', '0002_remove_park_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='mtb_trails_app.Trail'),
        ),
        migrations.AlterField(
            model_name='park',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='mtb_trails_app.State'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='mtb_trails_app.Park'),
        ),
    ]
